# Generated by Django 4.2.16 on 2025-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VibeCheckEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("added_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "song_selection",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Vibe Check Entry",
                "verbose_name_plural": "Vibe Check Entries",
            },
        ),
    ]
