# Generated by Django 4.2.16 on 2026-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_userprofile_design_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("book", "Reading"),
                            ("show", "Watching"),
                            ("game", "Playing"),
                            ("album", "Listening To"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("creator", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="highlights"),
                ),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Highlight",
                "verbose_name_plural": "Highlights",
            },
        ),
    ]
