# Generated by Django 4.2.16 on 2026-07-30 09:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_highlight"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("body", ckeditor.fields.RichTextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Work Section",
                "verbose_name_plural": "Work Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.CharField(blank=True, max_length=20, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talks",
                        to="main.worksection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talk",
                "verbose_name_plural": "Talks",
            },
        ),
    ]
